APP_MODE = "live"
AWS_REGION = "us-east-1"
AWS_ACCESS_KEY_ID = "AKIA4QQQVXUH7DVXX25K"
AWS_SECRET_ACCESS_KEY = "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"
AWS_SESSION_TOKEN = ""
S3_BUCKET = "adblitz-generated-assets"
BEDROCK_MODEL_ID = "amazon.nova-lite-v1:0"
NOVA_CANVAS_MODEL_ID = "amazon.nova-canvas-v1:0"
ELEVENLABS_API_KEY = "sk_21f72404775c845c64b46592aad88c1ded008efbab168e7f"
ELEVENLABS_VOICE_ID = ""